/**
 * Client-side behaviour for the goals board.
 *
 * Written as ES5-style string concatenation, matching every other client script
 * in this app. That is not only house style here: this source lives inside a TS
 * template literal, so a `${` in the client code would be interpolated at build
 * time. Only validated numbers are ever embedded.
 *
 * Drag uses Pointer Events rather than HTML5 drag-and-drop, which does not fire
 * on touch — supporting phones with HTML5 DnD would mean writing a second
 * implementation anyway. Pointer capture also keeps a drag alive when the
 * pointer leaves the card, avoiding the dragleave flicker.
 *
 * Neither approach is keyboard-operable, so the move menu is the accessible
 * path, not a garnish. It posts to the same endpoint as a drop.
 */

/** Shared helpers: identity, fetch, toasts. */
const CLIENT_PRELUDE = [
  "var CLIENT_ID = Math.random().toString(36).slice(2, 10);",
  "",
  "function toast(message, kind) {",
  "  if (typeof window.showToast === 'function') { window.showToast(message, kind || 'success'); }",
  "}",
  "",
  "// A signed-out session answers with an HTML 401, not JSON. Check before parsing",
  "// so an expired login reads as 'reload', not a console SyntaxError.",
  "function send(url, data) {",
  "  var body = data || {};",
  "  body.clientId = CLIENT_ID;",
  "  body.ajax = '1';",
  "  return fetch(url, {",
  "    method: 'POST',",
  "    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },",
  "    credentials: 'same-origin',",
  "    body: JSON.stringify(body)",
  "  }).then(function (res) {",
  "    var type = res.headers.get('content-type') || '';",
  "    if (type.indexOf('application/json') === -1) {",
  "      throw new Error(res.status === 401 ? 'Session expired — reload the page' : 'Something went wrong');",
  "    }",
  "    return res.json().then(function (payload) {",
  "      if (!res.ok || !payload.ok) { throw new Error(payload.error || 'Something went wrong'); }",
  "      return payload;",
  "    });",
  "  });",
  "}",
  "",
  "function fail(err) { toast(err && err.message ? err.message : 'Something went wrong', 'error'); }",
  "",
  "// Every rule in the stylesheet is scoped under .plugin-goals, so anything",
  "// created at runtime has to live inside the wrapper to pick up its styling.",
  "function root() { return document.querySelector('.goals-root') || document.body; }",
  "",
  "function formValues(form) {",
  "  var out = {};",
  "  var data = new FormData(form);",
  "  data.forEach(function (value, key) { out[key] = value; });",
  "  return out;",
  "}",
  "",
  "function openDialog(dialog) {",
  "  if (!dialog) return;",
  "  if (typeof dialog.showModal === 'function') { dialog.showModal(); }",
  "  else { dialog.setAttribute('open', 'open'); }",
  "}",
  "",
  "function closeDialog(dialog) {",
  "  if (!dialog) return;",
  "  if (typeof dialog.close === 'function') { dialog.close(); }",
  "  else { dialog.removeAttribute('open'); }",
  "}",
  "",
  "document.addEventListener('click', function (event) {",
  "  var closer = event.target.closest ? event.target.closest('[data-close-dialog]') : null;",
  "  if (closer) { event.preventDefault(); closeDialog(closer.closest('dialog')); }",
  "});",
].join('\n');

/** Board page: drag, move menu, dialogs, live refresh. */
function boardScript(boardId: number): string {
  return [
    CLIENT_PRELUDE,
    "",
    'var BOARD_ID = ' + String(boardId) + ';',
    "var region = document.getElementById('goals-region');",
    "var live = document.getElementById('goals-live');",
    "var dragging = false;",
    "var inFlight = 0;",
    "var pendingRefresh = false;",
    "var refreshTimer = null;",
    "var aborter = null;",
    "",
    "function announce(message) { if (live) { live.textContent = message; } }",
    "",
    "// ── Live refresh ────────────────────────────────────────────",
    "",
    "function settle() {",
    "  if (pendingRefresh && !dragging && inFlight === 0) { pendingRefresh = false; scheduleRefresh(); }",
    "}",
    "",
    "function scheduleRefresh() {",
    "  if (refreshTimer) { clearTimeout(refreshTimer); }",
    "  refreshTimer = setTimeout(refresh, 150);",
    "}",
    "",
    "function refresh() {",
    "  refreshTimer = null;",
    "  if (dragging || inFlight > 0) { pendingRefresh = true; return; }",
    "  if (aborter) { aborter.abort(); }",
    "  aborter = new AbortController();",
    "",
    "  var focused = document.activeElement;",
    "  var focusedId = focused && focused.getAttribute ? focused.getAttribute('data-card-id') : null;",
    "",
    "  fetch('/p/goals/b/' + BOARD_ID + '/fragment', {",
    "    credentials: 'same-origin',",
    "    signal: aborter.signal",
    "  }).then(function (res) {",
    "    if (!res.ok) { throw new Error('refresh failed'); }",
    "    return res.text();",
    "  }).then(function (html) {",
    "    // A drag may have started while this was in flight — never swap under it.",
    "    if (dragging || inFlight > 0) { pendingRefresh = true; return; }",
    "    region.innerHTML = html;",
    "    if (focusedId) {",
    "      var restored = region.querySelector('[data-card-id=\"' + focusedId + '\"]');",
    "      if (restored) { restored.focus(); }",
    "    }",
    "  }).catch(function () { /* aborted or offline — the next event resyncs */ });",
    "}",
    "",
    "if (typeof EventSource !== 'undefined') {",
    "  var stream = new EventSource('/p/goals/stream');",
    "  stream.addEventListener('board-changed', function (event) {",
    "    var data;",
    "    try { data = JSON.parse(event.data); } catch (err) { return; }",
    "    if (data.boardId !== BOARD_ID) return;",
    "    if (data.originId === CLIENT_ID) return;",
    "    if (dragging || inFlight > 0) { pendingRefresh = true; return; }",
    "    scheduleRefresh();",
    "  });",
    "}",
    "",
    "// ── Move ────────────────────────────────────────────────────",
    "",
    "function columnEls() { return Array.prototype.slice.call(region.querySelectorAll('.goals-column[data-column-id]')); }",
    "",
    "function cardsIn(columnEl) { return Array.prototype.slice.call(columnEl.querySelectorAll('.goals-card')); }",
    "",
    "function moveCard(cardId, toColumnId, toIndex, label) {",
    "  inFlight++;",
    "  return send('/p/goals/cards/move', {",
    "    cardId: cardId, toColumnId: toColumnId, toIndex: toIndex",
    "  }).then(function (payload) {",
    "    if (label) { toast('Moved to ' + label); announce(label + ', position ' + (payload.toIndex + 1)); }",
    "  }).catch(function (err) {",
    "    fail(err);",
    "    pendingRefresh = true;",
    "  }).then(function () {",
    "    inFlight--;",
    "    settle();",
    "  });",
    "}",
    "",
    "// ── Pointer drag ────────────────────────────────────────────",
    "",
    "var drag = null;",
    "",
    "function cacheGeometry() {",
    "  return columnEls().map(function (columnEl) {",
    "    return {",
    "      el: columnEl,",
    "      id: parseInt(columnEl.getAttribute('data-column-id'), 10),",
    "      name: columnEl.getAttribute('data-column-name') || '',",
    "      rect: columnEl.getBoundingClientRect(),",
    "      list: columnEl.querySelector('.goals-cards'),",
    "      cards: cardsIn(columnEl).map(function (cardEl) {",
    "        return { el: cardEl, rect: cardEl.getBoundingClientRect() };",
    "      })",
    "    };",
    "  });",
    "}",
    "",
    "function startDrag(cardEl, event) {",
    "  var rect = cardEl.getBoundingClientRect();",
    "  var ghost = cardEl.cloneNode(true);",
    "  ghost.classList.add('goals-ghost');",
    "  ghost.classList.remove('is-dragging');",
    "  ghost.style.width = rect.width + 'px';",
    "  root().appendChild(ghost);",
    "",
    "  var placeholder = document.createElement('li');",
    "  placeholder.className = 'goals-placeholder';",
    "  placeholder.style.height = rect.height + 'px';",
    "  cardEl.parentNode.insertBefore(placeholder, cardEl.nextSibling);",
    "",
    "  cardEl.classList.add('is-dragging');",
    "  dragging = true;",
    "",
    "  drag = {",
    "    cardEl: cardEl,",
    "    cardId: parseInt(cardEl.getAttribute('data-card-id'), 10),",
    "    fromColumnId: parseInt(cardEl.getAttribute('data-column-id'), 10),",
    "    ghost: ghost,",
    "    placeholder: placeholder,",
    "    offsetX: event.clientX - rect.left,",
    "    offsetY: event.clientY - rect.top,",
    "    x: event.clientX,",
    "    y: event.clientY,",
    "    frame: null,",
    "    geometry: cacheGeometry(),",
    "    target: { id: parseInt(cardEl.getAttribute('data-column-id'), 10), index: 0, name: '' },",
    "    scroller: region.querySelector('.goals-board-scroll')",
    "  };",
    "",
    "  paint();",
    "}",
    "",
    "function paint() {",
    "  if (!drag) return;",
    "  drag.frame = null;",
    "",
    "  drag.ghost.style.transform =",
    "    'translate3d(' + (drag.x - drag.offsetX) + 'px,' + (drag.y - drag.offsetY) + 'px,0)';",
    "",
    "  var column = null;",
    "  for (var i = 0; i < drag.geometry.length; i++) {",
    "    var candidate = drag.geometry[i];",
    "    if (drag.x >= candidate.rect.left && drag.x <= candidate.rect.right) { column = candidate; break; }",
    "  }",
    "  if (!column) { requestScroll(); return; }",
    "",
    "  var index = 0;",
    "  for (var j = 0; j < column.cards.length; j++) {",
    "    var entry = column.cards[j];",
    "    if (entry.el === drag.cardEl) continue;",
    "    if (drag.y > entry.rect.top + entry.rect.height / 2) { index++; }",
    "  }",
    "",
    "  if (drag.target.id !== column.id || drag.target.index !== index) {",
    "    drag.target = { id: column.id, index: index, name: column.name };",
    "    var visible = cardsIn(column.el).filter(function (el) { return el !== drag.cardEl; });",
    "    var before = visible[index] || null;",
    "    column.list.insertBefore(drag.placeholder, before);",
    "",
    "    drag.geometry.forEach(function (entry) { entry.el.classList.remove('is-drop-target'); });",
    "    column.el.classList.add('is-drop-target');",
    "  }",
    "",
    "  requestScroll();",
    "}",
    "",
    "function requestScroll() {",
    "  if (!drag || !drag.scroller) return;",
    "  var rect = drag.scroller.getBoundingClientRect();",
    "  var edge = 60;",
    "  if (drag.x < rect.left + edge) { drag.scroller.scrollLeft -= (rect.left + edge - drag.x) / 6; }",
    "  else if (drag.x > rect.right - edge) { drag.scroller.scrollLeft += (drag.x - rect.right + edge) / 6; }",
    "}",
    "",
    "function endDrag(commit) {",
    "  if (!drag) return;",
    "  var current = drag;",
    "  drag = null;",
    "  dragging = false;",
    "",
    "  if (current.frame) { cancelAnimationFrame(current.frame); }",
    "  if (current.ghost.parentNode) { current.ghost.parentNode.removeChild(current.ghost); }",
    "  current.cardEl.classList.remove('is-dragging');",
    "  current.geometry.forEach(function (entry) { entry.el.classList.remove('is-drop-target'); });",
    "",
    "  var moved = commit && (current.target.id !== current.fromColumnId || current.target.index !== originalIndex(current));",
    "",
    "  if (moved) {",
    "    current.placeholder.parentNode.insertBefore(current.cardEl, current.placeholder);",
    "    current.cardEl.setAttribute('data-column-id', String(current.target.id));",
    "    current.cardEl.classList.add('just-landed');",
    "    setTimeout(function () { current.cardEl.classList.remove('just-landed'); }, 320);",
    "  }",
    "",
    "  if (current.placeholder.parentNode) {",
    "    current.placeholder.parentNode.removeChild(current.placeholder);",
    "  }",
    "",
    "  if (moved) {",
    "    moveCard(current.cardId, current.target.id, current.target.index, current.target.name);",
    "  } else {",
    "    settle();",
    "  }",
    "}",
    "",
    "function originalIndex(current) {",
    "  var origin = null;",
    "  for (var i = 0; i < current.geometry.length; i++) {",
    "    if (current.geometry[i].id === current.fromColumnId) { origin = current.geometry[i]; break; }",
    "  }",
    "  if (!origin) return -1;",
    "  var index = 0;",
    "  for (var j = 0; j < origin.cards.length; j++) {",
    "    if (origin.cards[j].el === current.cardEl) { return index; }",
    "    index++;",
    "  }",
    "  return -1;",
    "}",
    "",
    "var armed = null;",
    "",
    "document.addEventListener('pointerdown', function (event) {",
    "  if (event.button !== 0 || event.ctrlKey) return;",
    "  var cardEl = event.target.closest ? event.target.closest('.goals-card') : null;",
    "  if (!cardEl || !region.contains(cardEl)) return;",
    "  if (event.target.closest('.goals-menu-trigger')) return;",
    "",
    "  var viaGrip = !!event.target.closest('.goals-grip');",
    "  armed = {",
    "    cardEl: cardEl,",
    "    pointerId: event.pointerId,",
    "    startX: event.clientX,",
    "    startY: event.clientY,",
    "    touch: event.pointerType !== 'mouse',",
    "    grip: viaGrip,",
    "    timer: null",
    "  };",
    "",
    "  // Touch needs deliberate intent, or the board could never be scrolled.",
    "  if (armed.touch && !viaGrip) {",
    "    armed.timer = setTimeout(function () {",
    "      if (armed && armed.cardEl === cardEl && !drag) {",
    "        cardEl.setPointerCapture(armed.pointerId);",
    "        startDrag(cardEl, { clientX: armed.startX, clientY: armed.startY });",
    "      }",
    "    }, 300);",
    "  }",
    "});",
    "",
    "document.addEventListener('pointermove', function (event) {",
    "  if (drag) {",
    "    event.preventDefault();",
    "    drag.x = event.clientX;",
    "    drag.y = event.clientY;",
    "    if (!drag.frame) { drag.frame = requestAnimationFrame(paint); }",
    "    return;",
    "  }",
    "  if (!armed || event.pointerId !== armed.pointerId) return;",
    "",
    "  var dx = Math.abs(event.clientX - armed.startX);",
    "  var dy = Math.abs(event.clientY - armed.startY);",
    "",
    "  if (armed.touch && !armed.grip) {",
    "    if (dx > 8 || dy > 8) { clearTimeout(armed.timer); armed = null; }",
    "    return;",
    "  }",
    "  if (dx > 6 || dy > 6) {",
    "    armed.cardEl.setPointerCapture(armed.pointerId);",
    "    startDrag(armed.cardEl, event);",
    "  }",
    "}, { passive: false });",
    "",
    "document.addEventListener('pointerup', function () {",
    "  if (armed && armed.timer) { clearTimeout(armed.timer); }",
    "  armed = null;",
    "  endDrag(true);",
    "});",
    "",
    "document.addEventListener('pointercancel', function () {",
    "  if (armed && armed.timer) { clearTimeout(armed.timer); }",
    "  armed = null;",
    "  endDrag(false);",
    "});",
    "",
    "document.addEventListener('visibilitychange', function () { if (document.hidden) { endDrag(false); } });",
    "",
    "// ── Move menu ───────────────────────────────────────────────",
    "",
    "var openMenu = null;",
    "",
    "function closeMenu() {",
    "  if (!openMenu) return;",
    "  if (openMenu.trigger) { openMenu.trigger.setAttribute('aria-expanded', 'false'); }",
    "  if (openMenu.el.parentNode) { openMenu.el.parentNode.removeChild(openMenu.el); }",
    "  openMenu = null;",
    "}",
    "",
    "function menuItem(label, disabled, onPick, color) {",
    "  var button = document.createElement('button');",
    "  button.type = 'button';",
    "  button.className = 'goals-menu-item';",
    "  button.setAttribute('role', 'menuitem');",
    "  button.disabled = !!disabled;",
    "  if (color) {",
    "    var dot = document.createElement('span');",
    "    dot.className = 'goals-menu-dot';",
    "    dot.style.background = color;",
    "    button.appendChild(dot);",
    "  }",
    "  button.appendChild(document.createTextNode(label));",
    "  button.addEventListener('click', function () { closeMenu(); onPick(); });",
    "  return button;",
    "}",
    "",
    "function showMenu(cardEl, trigger) {",
    "  closeMenu();",
    "",
    "  var cardId = parseInt(cardEl.getAttribute('data-card-id'), 10);",
    "  var columnEl = cardEl.closest('.goals-column');",
    "  var columnId = parseInt(columnEl.getAttribute('data-column-id'), 10);",
    "  var siblings = cardsIn(columnEl);",
    "  var index = siblings.indexOf(cardEl);",
    "  var title = cardEl.getAttribute('data-title') || 'Card';",
    "",
    "  var menu = document.createElement('div');",
    "  menu.className = 'goals-menu';",
    "  menu.setAttribute('role', 'menu');",
    "  menu.setAttribute('aria-label', 'Move ' + title);",
    "",
    "  var within = document.createElement('div');",
    "  within.className = 'goals-menu-label';",
    "  within.textContent = 'In this column';",
    "  menu.appendChild(within);",
    "",
    "  menu.appendChild(menuItem('Move up', index <= 0, function () {",
    "    moveCard(cardId, columnId, index - 1, null).then(refresh);",
    "  }));",
    "  menu.appendChild(menuItem('Move down', index >= siblings.length - 1, function () {",
    "    moveCard(cardId, columnId, index + 1, null).then(refresh);",
    "  }));",
    "  menu.appendChild(menuItem('Move to top', index <= 0, function () {",
    "    moveCard(cardId, columnId, 0, null).then(refresh);",
    "  }));",
    "  menu.appendChild(menuItem('Move to bottom', index >= siblings.length - 1, function () {",
    "    moveCard(cardId, columnId, siblings.length - 1, null).then(refresh);",
    "  }));",
    "",
    "  var others = columnEls().filter(function (el) {",
    "    return parseInt(el.getAttribute('data-column-id'), 10) !== columnId;",
    "  });",
    "",
    "  if (others.length) {",
    "    var label = document.createElement('div');",
    "    label.className = 'goals-menu-label';",
    "    label.textContent = 'Move to';",
    "    menu.appendChild(label);",
    "",
    "    others.forEach(function (el) {",
    "      var targetId = parseInt(el.getAttribute('data-column-id'), 10);",
    "      var name = el.getAttribute('data-column-name') || 'column';",
    "      var swatch = getComputedStyle(el).getPropertyValue('--goals-column-color');",
    "      menu.appendChild(menuItem(name, false, function () {",
    "        moveCard(cardId, targetId, 0, name).then(refresh);",
    "      }, swatch));",
    "    });",
    "  }",
    "",
    "  root().appendChild(menu);",
    "",
    "  var anchor = (trigger || cardEl).getBoundingClientRect();",
    "  var size = menu.getBoundingClientRect();",
    "  var left = Math.min(anchor.left, window.innerWidth - size.width - 8);",
    "  var top = anchor.bottom + 6;",
    "  if (top + size.height > window.innerHeight - 8) { top = Math.max(8, anchor.top - size.height - 6); }",
    "  menu.style.left = Math.max(8, left) + 'px';",
    "  menu.style.top = top + 'px';",
    "",
    "  openMenu = { el: menu, trigger: trigger, card: cardEl };",
    "  if (trigger) { trigger.setAttribute('aria-expanded', 'true'); }",
    "",
    "  var first = menu.querySelector('.goals-menu-item:not(:disabled)');",
    "  if (first) { first.focus(); }",
    "}",
    "",
    "document.addEventListener('click', function (event) {",
    "  var trigger = event.target.closest ? event.target.closest('.goals-menu-trigger') : null;",
    "  if (trigger) {",
    "    event.preventDefault();",
    "    event.stopPropagation();",
    "    var card = trigger.closest('.goals-card');",
    "    if (openMenu && openMenu.card === card) { closeMenu(); } else { showMenu(card, trigger); }",
    "    return;",
    "  }",
    "  if (openMenu && !event.target.closest('.goals-menu')) { closeMenu(); }",
    "});",
    "",
    "document.addEventListener('keydown', function (event) {",
    "  if (openMenu) {",
    "    var items = Array.prototype.slice.call(",
    "      openMenu.el.querySelectorAll('.goals-menu-item:not(:disabled)')",
    "    );",
    "    var at = items.indexOf(document.activeElement);",
    "    if (event.key === 'Escape') {",
    "      event.preventDefault();",
    "      var trigger = openMenu.trigger;",
    "      closeMenu();",
    "      if (trigger) { trigger.focus(); }",
    "      return;",
    "    }",
    "    if (event.key === 'ArrowDown') { event.preventDefault(); (items[at + 1] || items[0]).focus(); return; }",
    "    if (event.key === 'ArrowUp') { event.preventDefault(); (items[at - 1] || items[items.length - 1]).focus(); return; }",
    "    if (event.key === 'Home') { event.preventDefault(); items[0].focus(); return; }",
    "    if (event.key === 'End') { event.preventDefault(); items[items.length - 1].focus(); return; }",
    "    if (event.key === 'Tab') { closeMenu(); }",
    "    return;",
    "  }",
    "",
    "  if (event.key === 'Escape' && drag) { event.preventDefault(); endDrag(false); return; }",
    "",
    "  var cardEl = document.activeElement;",
    "  if (!cardEl || !cardEl.classList || !cardEl.classList.contains('goals-card')) return;",
    "",
    "  if (event.key === 'm' || event.key === 'M') {",
    "    event.preventDefault();",
    "    showMenu(cardEl, cardEl.querySelector('.goals-menu-trigger'));",
    "    return;",
    "  }",
    "  if (event.key === 'Enter') { event.preventDefault(); openCard(cardEl.getAttribute('data-card-id')); return; }",
    "",
    "  if (event.altKey && (event.key === 'ArrowUp' || event.key === 'ArrowDown')) {",
    "    event.preventDefault();",
    "    var columnEl = cardEl.closest('.goals-column');",
    "    var columnId = parseInt(columnEl.getAttribute('data-column-id'), 10);",
    "    var siblings = cardsIn(columnEl);",
    "    var index = siblings.indexOf(cardEl);",
    "    var next = event.key === 'ArrowUp' ? index - 1 : index + 1;",
    "    if (next < 0 || next >= siblings.length) return;",
    "    var name = columnEl.getAttribute('data-column-name') || '';",
    "    moveCard(parseInt(cardEl.getAttribute('data-card-id'), 10), columnId, next, null).then(function () {",
    "      announce(name + ', position ' + (next + 1) + ' of ' + siblings.length);",
    "      refresh();",
    "    });",
    "  }",
    "});",
    "",
    "// ── Card detail ─────────────────────────────────────────────",
    "",
    "var cardDialog = document.getElementById('goals-card-dialog');",
    "var cardBody = document.getElementById('goals-card-dialog-body');",
    "var cardTitle = document.getElementById('goals-card-dialog-title');",
    "",
    "function openCard(cardId) {",
    "  if (!cardDialog || !cardId) return;",
    "  cardBody.innerHTML = '<p class=\"goals-detail-empty\">Loading…</p>';",
    "  openDialog(cardDialog);",
    "  fetch('/p/goals/card/' + cardId + '/fragment', { credentials: 'same-origin' })",
    "    .then(function (res) {",
    "      if (!res.ok) { throw new Error(res.status === 401 ? 'Session expired — reload the page' : 'Could not open that goal'); }",
    "      return res.text();",
    "    })",
    "    .then(function (html) {",
    "      cardBody.innerHTML = html;",
    "      var titleInput = cardBody.querySelector('#goals-detail-title');",
    "      if (titleInput && cardTitle) { cardTitle.textContent = titleInput.value; }",
    "    })",
    "    .catch(function (err) {",
    "      closeDialog(cardDialog);",
    "      fail(err);",
    "    });",
    "}",
    "",
    "document.addEventListener('click', function (event) {",
    "  if (event.target.closest('.goals-card-actions')) return;",
    "  var cardEl = event.target.closest ? event.target.closest('.goals-card') : null;",
    "  if (cardEl && region.contains(cardEl)) { openCard(cardEl.getAttribute('data-card-id')); }",
    "});",
    "",
    "// ── Forms ───────────────────────────────────────────────────",
    "",
    "function submitJson(form, after) {",
    "  var values = formValues(form);",
    "  inFlight++;",
    "  return send(form.getAttribute('action'), values)",
    "    .then(function (payload) { if (after) { after(payload); } })",
    "    .catch(fail)",
    "    .then(function () { inFlight--; settle(); refresh(); });",
    "}",
    "",
    "document.addEventListener('submit', function (event) {",
    "  var form = event.target;",
    "  if (!form.getAttribute || !form.getAttribute('action')) return;",
    "  if (form.getAttribute('action').indexOf('/p/goals/') !== 0) return;",
    "",
    "  event.preventDefault();",
    "  var dialog = form.closest('dialog');",
    "  submitJson(form, function () {",
    "    if (dialog) { closeDialog(dialog); }",
    "    form.reset();",
    "    toast('Saved');",
    "  });",
    "});",
    "",
    "var newCardDialog = document.getElementById('goals-new-card-dialog');",
    "var newCardForm = document.getElementById('goals-new-card-form');",
    "var columnDialog = document.getElementById('goals-column-dialog');",
    "var columnForm = document.getElementById('goals-column-form');",
    "",
    "document.addEventListener('click', function (event) {",
    "  var addCard = event.target.closest ? event.target.closest('.goals-add-card') : null;",
    "  if (addCard && newCardForm) {",
    "    event.preventDefault();",
    "    newCardForm.elements.columnId.value = addCard.getAttribute('data-column-id');",
    "    openDialog(newCardDialog);",
    "    var titleField = document.getElementById('goals-new-card-title');",
    "    if (titleField) { titleField.focus(); }",
    "    return;",
    "  }",
    "",
    "  var addColumn = event.target.closest ? event.target.closest('.goals-add-column') : null;",
    "  if (addColumn && columnForm) {",
    "    event.preventDefault();",
    "    columnForm.setAttribute('action', '/p/goals/columns/create');",
    "    columnForm.elements.columnId.value = '';",
    "    columnForm.elements.name.value = '';",
    "    document.getElementById('goals-column-dialog-title').textContent = 'Add a column';",
    "    var deleteButton = columnForm.querySelector('.goals-column-delete');",
    "    if (deleteButton) { deleteButton.hidden = true; }",
    "    openDialog(columnDialog);",
    "    return;",
    "  }",
    "",
    "  var editColumn = event.target.closest ? event.target.closest('.goals-column-edit') : null;",
    "  if (editColumn && columnForm) {",
    "    event.preventDefault();",
    "    var columnEl = editColumn.closest('.goals-column');",
    "    columnForm.setAttribute('action', '/p/goals/columns/update');",
    "    columnForm.elements.columnId.value = editColumn.getAttribute('data-column-id');",
    "    columnForm.elements.name.value = columnEl.getAttribute('data-column-name') || '';",
    "    columnForm.elements.isDone.value = columnEl.getAttribute('data-is-done') === '1' ? '1' : '0';",
    "    document.getElementById('goals-column-dialog-title').textContent = 'Edit column';",
    "    var remove = columnForm.querySelector('.goals-column-delete');",
    "    if (remove) {",
    "      remove.hidden = false;",
    "      remove.setAttribute('data-column-id', editColumn.getAttribute('data-column-id'));",
    "      remove.setAttribute('data-card-count', String(cardsIn(columnEl).length));",
    "    }",
    "    openDialog(columnDialog);",
    "  }",
    "});",
    "",
    "document.addEventListener('click', function (event) {",
    "  var remove = event.target.closest ? event.target.closest('.goals-column-delete') : null;",
    "  if (!remove) return;",
    "  event.preventDefault();",
    "",
    "  var count = parseInt(remove.getAttribute('data-card-count'), 10) || 0;",
    "  var columnId = remove.getAttribute('data-column-id');",
    "  var others = columnEls().filter(function (el) {",
    "    return el.getAttribute('data-column-id') !== columnId;",
    "  });",
    "  if (!others.length) { fail(new Error('A board needs at least one column')); return; }",
    "",
    "  var mode = 'delete';",
    "  var targetColumnId = null;",
    "  if (count > 0) {",
    "    var keep = window.confirm(",
    "      'This column holds ' + count + ' card(s).\\n\\nOK: move them to ' +",
    "      (others[0].getAttribute('data-column-name') || 'the next column') +",
    "      '\\nCancel: delete them along with the column'",
    "    );",
    "    if (keep) { mode = 'move'; targetColumnId = parseInt(others[0].getAttribute('data-column-id'), 10); }",
    "  }",
    "",
    "  inFlight++;",
    "  send('/p/goals/columns/delete', {",
    "    columnId: parseInt(columnId, 10),",
    "    mode: mode,",
    "    targetColumnId: targetColumnId,",
    "    expectedCardCount: count",
    "  }).then(function () {",
    "    closeDialog(columnDialog);",
    "    toast('Column removed');",
    "  }).catch(fail).then(function () { inFlight--; settle(); refresh(); });",
    "});",
    "",
    "document.addEventListener('click', function (event) {",
    "  var remove = event.target.closest ? event.target.closest('.goals-card-delete') : null;",
    "  if (!remove) return;",
    "  event.preventDefault();",
    "  if (!window.confirm('Delete this goal and its comments?')) return;",
    "",
    "  inFlight++;",
    "  send('/p/goals/cards/delete', { cardId: parseInt(remove.getAttribute('data-card-id'), 10) })",
    "    .then(function () { closeDialog(cardDialog); toast('Goal deleted'); })",
    "    .catch(fail)",
    "    .then(function () { inFlight--; settle(); refresh(); });",
    "});",
    "",
    "document.addEventListener('click', function (event) {",
    "  var remove = event.target.closest ? event.target.closest('.goals-comment-delete') : null;",
    "  if (!remove) return;",
    "  event.preventDefault();",
    "",
    "  inFlight++;",
    "  send('/p/goals/comments/delete', { commentId: parseInt(remove.getAttribute('data-comment-id'), 10) })",
    "    .then(function () {",
    "      var item = remove.closest('.goals-comment');",
    "      if (item && item.parentNode) { item.parentNode.removeChild(item); }",
    "      toast('Comment deleted');",
    "    })",
    "    .catch(fail)",
    "    .then(function () { inFlight--; settle(); });",
    "});",
    "",
    "// Changing the column in the detail form is a move, not a field update.",
    "document.addEventListener('change', function (event) {",
    "  var select = event.target;",
    "  if (!select.id || select.id !== 'goals-detail-column') return;",
    "",
    "  var form = select.closest('.goals-card-form');",
    "  if (!form) return;",
    "  var cardId = parseInt(form.getAttribute('data-card-id'), 10);",
    "  var toColumnId = parseInt(select.value, 10);",
    "  var name = select.options[select.selectedIndex].textContent;",
    "  select.setAttribute('data-current', String(toColumnId));",
    "  moveCard(cardId, toColumnId, 0, name).then(refresh);",
    "});",
    "",
    "// ── Board settings ──────────────────────────────────────────",
    "",
    "var settings = document.getElementById('goals-board-settings');",
    "var boardDialog = document.getElementById('goals-board-dialog');",
    "if (settings && boardDialog) {",
    "  settings.addEventListener('click', function () { openDialog(boardDialog); });",
    "}",
    "",
    "var boardDelete = document.getElementById('goals-board-delete');",
    "if (boardDelete) {",
    "  boardDelete.addEventListener('click', function () {",
    "    var title = boardDelete.getAttribute('data-board-title') || '';",
    "    var typed = window.prompt('Deleting a board removes every column, card and comment on it.\\n\\nType the board name to confirm:');",
    "    if (typed === null) return;",
    "    if (typed !== title) { fail(new Error('That name did not match')); return; }",
    "",
    "    send('/p/goals/boards/delete', { boardId: BOARD_ID, confirm: typed })",
    "      .then(function () { window.location.href = '/p/goals/'; })",
    "      .catch(fail);",
    "  });",
    "}",
  ].join('\n');
}

export function boardClientJs(boardId: number): string {
  return '<script>(function () {\n' + boardScript(boardId) + '\n})();</script>';
}

export const INDEX_CLIENT_JS =
  '<script>(function () {\n' +
  [
    CLIENT_PRELUDE,
    "",
    "var dialog = document.getElementById('goals-new-board-dialog');",
    "['goals-new-board', 'goals-new-board-empty'].forEach(function (id) {",
    "  var button = document.getElementById(id);",
    "  if (button) {",
    "    button.addEventListener('click', function () {",
    "      openDialog(dialog);",
    "      var field = document.getElementById('goals-board-title');",
    "      if (field) { field.focus(); }",
    "    });",
    "  }",
    "});",
    "",
    "document.addEventListener('submit', function (event) {",
    "  var form = event.target;",
    "  if (!form.getAttribute || form.getAttribute('action') !== '/p/goals/boards/create') return;",
    "  event.preventDefault();",
    "  send('/p/goals/boards/create', formValues(form))",
    "    .then(function (payload) { window.location.href = '/p/goals/b/' + payload.boardId; })",
    "    .catch(fail);",
    "});",
  ].join('\n') +
  '\n})();</script>';

export const MEMBERS_CLIENT_JS =
  '<script>(function () {\n' +
  [
    "var picker = document.getElementById('goals-member-color');",
    "document.addEventListener('click', function (event) {",
    "  var swatch = event.target.closest ? event.target.closest('.goals-swatch') : null;",
    "  if (swatch && picker) { picker.value = swatch.getAttribute('data-color'); }",
    "});",
  ].join('\n') +
  '\n})();</script>';
